# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QY0RaGQO90OoVTUJaFyMS5LBHgHCeV3N
"""

#display date and time using python
import datetime

now = datetime.datetime.now()

# Display a specific message
print("Current date and time : ")

# Print the current date and time in a specific format
print(now.strftime("%Y-%m-%d %H:%M:%S"))

from math import pi

# Ask the user to input the radius
r = float(input("Input the radius of the circle : "))

# Calculate by using the formula "area = π * r^2"
area = pi * r ** 2

# Display the result
print("The area of the circle with radius " + str(r) + " is: " + str(area))

# to print name in reverse order

#ask your to input first name
first_name= input("write your first name: ")

# ask user to write last name
last_name= input("write your last name: ")

#print last name first
print(last_name +" "+ first_name)

# make a list and display 1st and last value
color_list = ["Red","Green","White" ,"Black"]

#to display show their index in code
print(color_list[0], color_list[-1])

#display the exam start date
exam_st_date = (11, 12, 2014)

print("The examination will start from : %i / %i / %i" % exam_st_date)

a = int(input("Input an integer: "))

# Create new integers 'n1', 'n2', and 'n3'

 # Convert 'a' to an integer
n1 = int("%s" % a)

 # Add 'a' with itself and convert to integer
n2 = int("%s%s" % (a, a))

# Add 'a' with itself twice
n3 = int("%s%s%s" % (a, a, a))

# Calculate the sum
print(n1 + n2 + n3)